server:
  port: ${APP_SERVICE_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: telegram-bot-spring

  data:
    mongodb:
      uri: ${APP_MONGODB_URI:uri}
      database: ${APP_MONGODB_DATABASE:app-telegram-db}

telegram:
  bot:
    username: ${APP_TELEGRAM_BOT_USERNAME:bot_name}
    token: ${APP_TELEGRAM_BOT_TOKEN:app_token}

management:
  endpoints:
    web:
      exposure:
        include:
          - health

springdoc:
  swagger-ui:
    path: /api/documentation

jwt:
  app:
    secret: ${JWT_SECRET_KEY:jwt_key}